const images = {
  logo: "/image/logo.png",
  logotron: "/image/logotron.png",
  hoitruong: "/image/hoitruong.jpg",
  b: "/image/b.jpg",
  c: "/image/c.jpg",
  bs: "/image/bs.png",
  c1: "/image/c1.jpg",

  webLogo: "/images/web_logo.png",
  rating: "/images/rating.png",
  product: "/images/sanpham.png",
  start: "/images/star.png",
  bannerSlide: "/images/banner/bannerSlide.png",
  bannerSlide1: "/images/banner/bannerSlide1.png",
  productGr1995: "/images/product/productGr1995.png",
  bannerAds: "/images/banner/bannerAds.png",
  bannerAds1: "/images/banner/bannerAds1.png",
  whyChooseUs: "/images/banner/whyChooseUs.png",
  brandexm: "/images/featuredBrands/brandexm.png",
  backgroundBlog: "/images/blogs/backgroundBlogs.png",
  aboutUs: "/images/about-us/about_us.jpg",
  cermark: "/images/about-us/cemark.png",
  fda: "/images/about-us/fda.png",
  iso9001: "/images/about-us/iso9001.jpg",
  vietnamStandard: "/images/about-us/vietnam-standard.png",
  pocari: "/images/product/pocari.jpg",
  pocari_1: "/images/product/pocari_1.jpg",
  pocari_2: "/images/product/pocari_2.jpg",
  pocari_3: "/images/product/pocari_3.jpg",
  pocari_4: "/images/product/pocari_4.jpg",
  pocari_5: "/images/product/pocari_5.jpg",
  pocari_6: "/images/product/pocari_6.jpg",
  pocari_7: "/images/product/pocari_7.jpg",
  pocari_8: "/images/product/pocari_8.jpg",
  default_avatar: "/images/avatar/default-avatar.jpg",
  anh_local: "/images/anh_local.png",
};

export default images;
